function varargout= system_dependent(varargin)
  if (nargin == 2) && (strcmpi(varargin{1}, 'lmfeaturelist')) && (varargin{2} == 2)
     varargout{1} = { ... 
        'compiler'; ...
        'curve_fitting_toolbox'; ...
        'distrib_computing_toolbox'; ...
        'gpu_coder'; ...
        'image_toolbox'; ...
        'matlab'; ...
        'matlab_builder_for_java'; ...
        'matlab_coder'; ...
        'neural_network_toolbox'; ...
        'optimization_toolbox'; ...
        'signal_toolbox'; ...
        'statistics_toolbox'; ...
        'video_and_image_blockset'; ...
        'wavelet_toolbox'; ...
            };
  else 
     error(nargoutchk(0,3,nargout,'string'));
     if nargout==0 
          builtin('system_dependent', varargin{:});
     elseif nargout==1 
          varargout{1}=builtin('system_dependent', varargin{:});
     elseif nargout==2 
          [varargout{1},varargout{2}]=builtin('system_dependent', varargin{:});
     elseif nargout==3 
          [varargout{1},varargout{2},varargout{3}]=builtin('system_dependent', varargin{:});
     end 
  end 
